### ISSUE TITLE
& in scanf

### ISSUE THREAD

**Issue by cbarkinozer** [abbaselmas/cen215DataStructureLab#1]
https://github.com/abbaselmas/cen215DataStructureLab/blob/0363486b7854defee0d5b52b7ad18bc4426ab16e/2InsertDeleteReverse/InsertDeleteReverse/Source.c#L61

**Comment by abbaselmas** [comment]
**a** is already a pointer which just shows address, incrementing pointer is incrementing adress. There is nothing wrong here.
